<?php

/**
 * @file
 * Contains cloudflare.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cloudflare_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cloudflare module.
    case 'help.page.cloudflare':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('CloudFlare CDN integration.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_requirements().
 */
function address_requirements($phase) {
  $requirements = [];
  if ($phase == 'install') {
    if (!class_exists('\CloudFlarePhpSdk\ApiEndpoints\ZoneApi')) {
      $requirements['cloudflare_library'] = [
        'description' => t('Address requires the d8-contrib-modules/cloudflarephpsdk library.'),
        'severity' => REQUIREMENT_ERROR,
      ];
    }
  }
  return $requirements;
}
