<?php
/**
 * @file
 * Contains cloudflare_zone_ui.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cloudflare_zone_ui_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cloudflare module.
    case 'help.page.cloudflare.zonesettings':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('CloudFlare CDN integration.') . '</p>';
      return $output;

    default:
  }
}
